/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ImportRouteImport } from './routes/import'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsJoRouteImport } from './routes/reports.jo'
import { Route as ReportsCarlRouteImport } from './routes/reports.carl'
import { Route as PlatformPlatformIdRouteImport } from './routes/platform.$platformId'
import { Route as AgentPlatformIdAgentIdRouteImport } from './routes/agent.$platformId.$agentId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)

const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsJoRoute = ReportsJoRouteImport.update({
  id: '/jo',
  path: '/jo',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsCarlRoute = ReportsCarlRouteImport.update({
  id: '/carl',
  path: '/carl',
  getParentRoute: () => ReportsRoute,
} as any)
const PlatformPlatformIdRoute = PlatformPlatformIdRouteImport.update({
  id: '/platform/$platformId',
  path: '/platform/$platformId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPlatformIdAgentIdRoute = AgentPlatformIdAgentIdRouteImport.update({
  id: '/agent/$platformId/$agentId',
  path: '/agent/$platformId/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/trends': typeof TrendsRoute
  '/reports': typeof ReportsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/platform/$platformId': typeof PlatformPlatformIdRoute
  '/reports/carl': typeof ReportsCarlRoute
  '/reports/jo': typeof ReportsJoRoute
  '/agent/$platformId/$agentId': typeof AgentPlatformIdAgentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/trends': typeof TrendsRoute
  '/reports': typeof ReportsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/platform/$platformId': typeof PlatformPlatformIdRoute
  '/reports/carl': typeof ReportsCarlRoute
  '/reports/jo': typeof ReportsJoRoute
  '/agent/$platformId/$agentId': typeof AgentPlatformIdAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/trends': typeof TrendsRoute
  '/reports': typeof ReportsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/platform/$platformId': typeof PlatformPlatformIdRoute
  '/reports/carl': typeof ReportsCarlRoute
  '/reports/jo': typeof ReportsJoRoute
  '/agent/$platformId/$agentId': typeof AgentPlatformIdAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/import'
    | '/reports'
    | '/sitemap.xml'
    | '/platform/$platformId'
    | '/reports/carl'
    | '/reports/jo'
    | '/agent/$platformId/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/import'
    | '/reports'
    | '/sitemap.xml'
    | '/platform/$platformId'
    | '/reports/carl'
    | '/reports/jo'
    | '/agent/$platformId/$agentId'
  id:
    | '__root__'
    | '/'
    | '/import'
    | '/reports'
    | '/sitemap.xml'
    | '/platform/$platformId'
    | '/reports/carl'
    | '/reports/jo'
    | '/agent/$platformId/$agentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportRoute: typeof ImportRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PlatformPlatformIdRoute: typeof PlatformPlatformIdRoute
  AgentPlatformIdAgentIdRoute: typeof AgentPlatformIdAgentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/jo': {
      id: '/reports/jo'
      path: '/jo'
      fullPath: '/reports/jo'
      preLoaderRoute: typeof ReportsJoRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/carl': {
      id: '/reports/carl'
      path: '/carl'
      fullPath: '/reports/carl'
      preLoaderRoute: typeof ReportsCarlRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/platform/$platformId': {
      id: '/platform/$platformId'
      path: '/platform/$platformId'
      fullPath: '/platform/$platformId'
      preLoaderRoute: typeof PlatformPlatformIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$platformId/$agentId': {
      id: '/agent/$platformId/$agentId'
      path: '/agent/$platformId/$agentId'
      fullPath: '/agent/$platformId/$agentId'
      preLoaderRoute: typeof AgentPlatformIdAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReportsRouteChildren {
  ReportsCarlRoute: typeof ReportsCarlRoute
  ReportsJoRoute: typeof ReportsJoRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsCarlRoute: ReportsCarlRoute,
  ReportsJoRoute: ReportsJoRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TrendsRoute: TrendsRoute,
  ImportRoute: ImportRoute,
  ReportsRoute: ReportsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PlatformPlatformIdRoute: PlatformPlatformIdRoute,
  AgentPlatformIdAgentIdRoute: AgentPlatformIdAgentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
