/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReportsJoRouteImport } from './routes/reports.jo'
import { Route as ReportsCarlRouteImport } from './routes/reports.carl'
import { Route as ImportRouteImport } from './routes/import'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformPlatformIdRouteImport } from './routes/platform.$platformId'
import { Route as AgentPlatformIdAgentIdRouteImport } from './routes/agent.$platformId.$agentId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)

const ReportsJoRoute = ReportsJoRouteImport.update({
  id: '/reports/jo',
  path: '/reports/jo',
  getParentRoute: () => rootRouteImport,
} as any)

const ReportsCarlRoute = ReportsCarlRouteImport.update({
  id: '/reports/carl',
  path: '/reports/carl',
  getParentRoute: () => rootRouteImport,
} as any)

const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const PlatformPlatformIdRoute = PlatformPlatformIdRouteImport.update({
  id: '/platform/$platformId',
  path: '/platform/$platformId',
  getParentRoute: () => rootRouteImport,
} as any)

const AgentPlatformIdAgentIdRoute = AgentPlatformIdAgentIdRouteImport.update({
  id: '/agent/$platformId/$agentId',
  path: '/agent/$platformId/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/reports': typeof ReportsRoute
  '/reports/jo': typeof ReportsJoRoute
  '/reports/carl': typeof ReportsCarlRoute
  '/platform/$platformId': typeof PlatformPlatformIdRoute
  '/agent/$platformId/$agentId': typeof AgentPlatformIdAgentIdRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/reports': typeof ReportsRoute
  '/reports/jo': typeof ReportsJoRoute
  '/reports/carl': typeof ReportsCarlRoute
  '/platform/$platformId': typeof PlatformPlatformIdRoute
  '/agent/$platformId/$agentId': typeof AgentPlatformIdAgentIdRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/reports': typeof ReportsRoute
  '/reports/jo': typeof ReportsJoRoute
  '/reports/carl': typeof ReportsCarlRoute
  '/platform/$platformId': typeof PlatformPlatformIdRoute
  '/agent/$platformId/$agentId': typeof AgentPlatformIdAgentIdRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/import'
    | '/reports'
    | '/reports/jo'
    | '/reports/carl'
    | '/platform/$platformId'
    | '/agent/$platformId/$agentId'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/import'
    | '/reports'
    | '/reports/jo'
    | '/reports/carl'
    | '/platform/$platformId'
    | '/agent/$platformId/$agentId'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/import'
    | '/reports'
    | '/reports/jo'
    | '/reports/carl'
    | '/platform/$platformId'
    | '/agent/$platformId/$agentId'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportRoute: typeof ImportRoute
  ReportsRoute: typeof ReportsRoute
  ReportsJoRoute: typeof ReportsJoRoute
  ReportsCarlRoute: typeof ReportsCarlRoute
  PlatformPlatformIdRoute: typeof PlatformPlatformIdRoute
  AgentPlatformIdAgentIdRoute: typeof AgentPlatformIdAgentIdRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportRoute: ImportRoute,
  ReportsRoute: ReportsRoute,
  ReportsJoRoute: ReportsJoRoute,
  ReportsCarlRoute: ReportsCarlRoute,
  PlatformPlatformIdRoute: PlatformPlatformIdRoute,
  AgentPlatformIdAgentIdRoute: AgentPlatformIdAgentIdRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
