/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformPlatformIdRouteImport } from './routes/platform.$platformId'
import { Route as AgentPlatformIdAgentIdRouteImport } from './routes/agent.$platformId.$agentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformPlatformIdRoute = PlatformPlatformIdRouteImport.update({
  id: '/platform/$platformId',
  path: '/platform/$platformId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPlatformIdAgentIdRoute = AgentPlatformIdAgentIdRouteImport.update({
  id: '/agent/$platformId/$agentId',
  path: '/agent/$platformId/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/platform/$platformId': typeof PlatformPlatformIdRoute
  '/agent/$platformId/$agentId': typeof AgentPlatformIdAgentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/platform/$platformId': typeof PlatformPlatformIdRoute
  '/agent/$platformId/$agentId': typeof AgentPlatformIdAgentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/platform/$platformId': typeof PlatformPlatformIdRoute
  '/agent/$platformId/$agentId': typeof AgentPlatformIdAgentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/platform/$platformId' | '/agent/$platformId/$agentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/platform/$platformId' | '/agent/$platformId/$agentId'
  id: '__root__' | '/' | '/platform/$platformId' | '/agent/$platformId/$agentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlatformPlatformIdRoute: typeof PlatformPlatformIdRoute
  AgentPlatformIdAgentIdRoute: typeof AgentPlatformIdAgentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/$platformId': {
      id: '/platform/$platformId'
      path: '/platform/$platformId'
      fullPath: '/platform/$platformId'
      preLoaderRoute: typeof PlatformPlatformIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$platformId/$agentId': {
      id: '/agent/$platformId/$agentId'
      path: '/agent/$platformId/$agentId'
      fullPath: '/agent/$platformId/$agentId'
      preLoaderRoute: typeof AgentPlatformIdAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlatformPlatformIdRoute: PlatformPlatformIdRoute,
  AgentPlatformIdAgentIdRoute: AgentPlatformIdAgentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
